site_name: MkDocs Youtube Tutorial
theme:
  name: material
  custom_dir: overrides
  favicon: image/cowboy-hat.png
  features:
    - navigation.tabs
    - navigation.sections

    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    logo: fontawesome/solid/hat-cowboy
  language: en
 
 
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Latifa-Ajram/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/latifa.aj1/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/latifa-ajram/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href=" https://github.com/Latifa-Ajram/"  target="_blank" rel="noopener">Latifa Ajram</a>
 




